"""create initial schema

Revision ID: 45e1098fc22f
Revises: 
Create Date: 2026-08-11 18:19:38.132778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e1098fc22f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'assignment_date', name='uq_driver_assignment_date')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('hours_on_duty', sa.Float(), nullable=True),
    sa.Column('trips_completed', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('RESOLVED', 'RESOLVED_WITH_FLAGS', 'REVIEW_REQUIRED', name='summarystatus'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'summary_date', name='uq_driver_summary_date')
    )
    op.create_table('dispatch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=30), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TRIP_ASSIGNED', 'TRIP_COMPLETED', name='dispatcheventtype'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gps_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('LOGIN', 'LOGOUT', name='shifteventtype'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=30), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=False),
    sa.Column('planned_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=False),
    sa.Column('actual_end', sa.DateTime(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=20), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'INFORMATIONAL', name='exceptionseverity'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['daily_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exceptions')
    op.drop_table('trips')
    op.drop_table('shifts')
    op.drop_table('shift_events')
    op.drop_table('gps_pings')
    op.drop_table('fuel_swipes')
    op.drop_table('dispatch_events')
    op.drop_table('daily_summaries')
    op.drop_table('assignments')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    # ### end Alembic commands ###
